### ISSUE TITLE
Not Able to install Data Explorer

### ISSUE THREAD

**Issue by Bhanupodila** [dataexplorer/dataexplorer#1]
Hi,

I am not able to install data explorer, can you please help me?
I am getting below errors and my machine is of windows 64 bit.

PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.1
	System.Deployment.dll 		: 4.0.30319.1 (RTMRel.030319-0100)
	clr.dll 			: 4.0.30319.1 (RTMRel.030319-0100)
	dfdll.dll 			: 4.0.30319.1 (RTMRel.030319-0100)
	dfshim.dll 			: 4.0.31106.0 (Main.031106-0000)

SOURCES
	Deployment url			: file:///C:/Users/ADMIN/Downloads/DataExplorer%20(2).application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\ADMIN\Downloads\DataExplorer (2).application resulted in exception. Following failure messages were detected:
		+ Exception reading manifest from file:///C:/Users/ADMIN/Downloads/DataExplorer%20(2).application: the manifest may not be valid or the file could not be opened.
		+ Manifest XML signature is not valid.
		+ SignatureDescription could not be created for the signature algorithm supplied.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [2/3/2017 6:08:52 PM] : Activation of C:\Users\ADMIN\Downloads\DataExplorer (2).application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [2/3/2017 6:08:53 PM] System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Exception reading manifest from file:///C:/Users/ADMIN/Downloads/DataExplorer%20(2).application: the manifest may not be valid or the file could not be opened.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (SignatureValidation)
		- Manifest XML signature is not valid.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSignature(Stream s)
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
		--- Inner Exception ---
		System.Security.Cryptography.CryptographicException
		- SignatureDescription could not be created for the signature algorithm supplied.
		- Source: System.Security
		- Stack trace:
			at System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm key)
			at System.Security.Cryptography.Xml.SignedXml.CheckSignature(AsymmetricAlgorithm key)
			at System.Security.Cryptography.Xml.SignedXml.CheckSignatureReturningKey(AsymmetricAlgorithm& signingKey)
			at System.Deployment.Internal.CodeSigning.SignedCmiManifest.Verify(CmiManifestVerifyFlags verifyFlags)
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSignature(Stream s)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by matthewrenze** [comment]
@Bhanupodila 

It looks like there is an issue with the ClickOnce installer.

As a workaround, here is a link to a zip file containing all of the files that get installed on your machine by the installer:
https://dl.dropboxusercontent.com/u/31704806/Data%20Explorer%20v0.2.0.zip

You should be able to unzip these files and run "DataExplorer.exe" by double clicking on the file.

I hope this helps!
